import { makeStyles } from "@/theme";

export const useTransactionsStyles = makeStyles(
  ({ colors, spacing, radius, typography }) => ({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background.screen,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: spacing[5],
      height: 56,
      backgroundColor: colors.background.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.default,
    },
    headerTitle: {
      fontSize: typography.fontSize.xl,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[2],
    },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    filterDot: {
      position: "absolute",
      top: 8,
      right: 10,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary.main,
    },
    summaryLine: {
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[3],
    },
    summaryText: {
      fontSize: 12,
      fontFamily: typography.fontFamily.Manrope.Bold,
      letterSpacing: 0.5,
      color: colors.text.secondary,
      textTransform: "uppercase",
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[4],
      paddingBottom: 120,
    },
    scrollContentEmpty: {
      flexGrow: 1,
      justifyContent: "center",
      paddingBottom: 80,
    },
    section: {
      marginBottom: spacing[4],
    },
    sectionLabel: {
      fontSize: 12,
      fontFamily: typography.fontFamily.Manrope.Bold,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      color: colors.text.secondary,
      marginBottom: spacing[2],
      paddingHorizontal: spacing[1],
    },
    transactionRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: spacing[4],
    },
    transactionLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[4],
    },
    txIconWrap: {
      width: 40,
      height: 40,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    txInfo: {
      gap: 2,
    },
    txTitle: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
    },
    txSubtitle: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Regular,
      color: colors.text.secondary,
    },
    txAmount: {
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Bold,
    },
    divider: {
      height: 1,
      backgroundColor: `${colors.border.default}40`,
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[8],
    },
    emptyIconWrap: {
      width: 96,
      height: 96,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border.default,
      marginBottom: spacing[6],
    },
    emptyTitle: {
      fontSize: typography.fontSize.xl,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
      textAlign: "center",
      marginBottom: spacing[2],
    },
    emptySubtitle: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Regular,
      color: colors.text.secondary,
      textAlign: "center",
      maxWidth: 320,
      marginBottom: spacing[6],
    },
    emptyBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[2],
      backgroundColor: colors.primary.main,
      paddingHorizontal: spacing[6],
      paddingVertical: spacing[3.5],
      borderRadius: radius.full,
    },
    emptyBtnText: {
      fontSize: 12,
      fontFamily: typography.fontFamily.Manrope.Bold,
      letterSpacing: 0.5,
      color: colors.primary.contrastText,
      textTransform: "uppercase",
    },
    // Search styles
    searchHeader: {
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[3],
      backgroundColor: colors.background.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.default,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: radius.full,
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[1],
    },
    searchIconBtn: {
      padding: spacing[1],
    },
    searchInput: {
      flex: 1,
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Regular,
      paddingHorizontal: spacing[2],
    },
  }),
);
