import { makeStyles } from "@/theme";

export const useTransactionsStyles = makeStyles(
  ({ colors, spacing, radius, typography }) => ({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background.screen,
    },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[3],
      paddingHorizontal: spacing[4],
      marginBottom: spacing[5],
      marginTop: spacing[2.5],
    },
    filterBtnWrap: {
      position: "relative",
    },
    filterBtn: {
      width: 48,
      height: 48,
      borderRadius: radius.lg,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary.main,
    },
    filterActiveDot: {
      position: "absolute",
      top: -8,
      right: -3,
      width: 20,
      height: 20,
      borderRadius: radius.full,
      borderWidth: 2,
      backgroundColor: colors.background.surfaceAlt,
      borderColor: colors.background.surfaceAlt,
    },
    scroll: {
      flex: 1,
      paddingVertical: spacing[2.5],
    },
    scrollContent: {
      paddingHorizontal: spacing[4],
      paddingBottom: 120,
    },
    scrollContentEmpty: {
      flexGrow: 1,
      justifyContent: "center",
      paddingBottom: 80,
    },
    emptyState: {
      alignItems: "center",
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[6],
    },
    emptyIllustrationWrap: {
      maxWidth: "100%",
      alignItems: "center",
    },
    emptyTitle: {
      marginTop: spacing[4],
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Bold,
      textAlign: "center",
      color: colors.text.primary,
    },
    emptySubtitle: {
      marginTop: spacing[2],
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Medium,
      textAlign: "center",
      lineHeight: 20,
      color: colors.text.secondary,
    },
    feedbackCard: {
      borderRadius: radius.xl,
      borderWidth: 1,
      paddingVertical: spacing[5],
      paddingHorizontal: spacing[4],
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing[3],
      backgroundColor: colors.background.surfaceAlt,
      borderColor: colors.border.default,
    },
    feedbackTitle: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
      textAlign: "center",
      color: colors.text.primary,
    },
    feedbackSubtitle: {
      marginTop: spacing[1.5],
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Medium,
      textAlign: "center",
      color: colors.text.secondary,
    },
    section: {
      marginBottom: spacing[6],
    },
    sectionLabel: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      letterSpacing: 0.5,
      marginBottom: spacing[3],
      color: colors.text.secondary,
    },
    card: {
      flexDirection: "row",
      alignItems: "center",
      padding: spacing[3.5],
      borderRadius: radius.lg,
      borderWidth: 1,
      marginBottom: spacing[2.5],
      backgroundColor: colors.background.surfaceAlt,
      borderColor: colors.border.default,
    },
    txIconWrap: {
      width: 52,
      height: 52,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginRight: spacing[3],
    },
    txIconInner: {
      width: 42,
      height: 42,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    txBody: {
      flex: 1,
      minWidth: 0,
    },
    txTitle: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.text.primary,
    },
    txSubtitle: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.Medium,
      marginTop: spacing[0.5],
      color: colors.text.secondary,
    },
    amountWrap: {
      alignItems: "flex-end",
      marginLeft: spacing[2],
    },
    txAmount: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Bold,
      textAlign: "right",
    },
    txTime: {
      fontSize: 10,
      marginTop: spacing[0.5],
      fontFamily: typography.fontFamily.Manrope.Medium,
      color: colors.text.secondary,
    },
  }),
);
