import { makeStyles } from "@/theme";

export const useAddExpensesStyles = makeStyles(
  ({ colors, spacing, radius, typography }) => ({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background.screen,
    },
    flex: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: spacing[2],
      paddingVertical: spacing[3],
      minHeight: 48,
      backgroundColor: colors.background.screen,
    },
    backBtn: {
      padding: spacing[2],
    },
    headerTitle: {
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
    },
    headerRight: {
      width: 40,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: spacing[6],
      paddingBottom: spacing[6],
    },

    // ── Existing keys used by sub-components — unchanged ──────────
    incomeCard: {
      borderRadius: radius.lg,
      borderWidth: 1,
      padding: spacing[4],
      marginBottom: spacing[6],
      shadowColor: colors.palette.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
      backgroundColor: colors.background.surfaceAlt,
      borderColor: colors.border.default,
    },
    incomeCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing[1.5],
    },
    incomeCardLabel: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      color: colors.text.secondary,
    },
    incomeCardTotal: {
      fontSize: typography.fontSize["2xl"],
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
    },
    incomeCardTotalSuffix: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Medium,
      color: colors.text.secondary,
    },
    incomeCardBarWrap: {
      height: 8,
      borderRadius: radius.sm,
      flexDirection: "row",
      overflow: "hidden",
      marginTop: spacing[3],
      marginBottom: spacing[2.5],
      backgroundColor: colors.background.surface,
    },
    incomeCardBarGreen: {
      height: "100%",
      borderRadius: radius.sm,
      borderTopRightRadius: 0,
      borderBottomRightRadius: 0,
      backgroundColor: colors.status.success.main,
    },
    incomeCardBarRed: {
      height: "100%",
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      backgroundColor: colors.status.error.main,
    },
    incomeCardFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    incomeCardRemaining: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.text.secondary,
    },
    incomeCardPercent: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.Medium,
      color: colors.text.muted,
    },

    // ── Hero amount — redesigned ───────────────────────────────────
    amountSection: {
      marginTop: spacing[6],
      marginBottom: spacing[5],
      alignItems: "center",
    },
    typeChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[1.5],
      alignSelf: "center",
      paddingVertical: spacing[1.5],
      paddingHorizontal: spacing[3],
      borderRadius: radius.full,
      backgroundColor: colors.status.error.main + "14",
      marginBottom: spacing[3],
    },
    typeChipText: {
      fontSize: 11,
      fontFamily: typography.fontFamily.Manrope.Bold,
      letterSpacing: 0.8,
      textTransform: "uppercase",
      color: colors.status.error.main,
    },
    amountLabel: {
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Medium,
      letterSpacing: 0.5,
      textTransform: "uppercase",
      marginBottom: spacing[2],
      textAlign: "center",
      color: colors.text.secondary,
    },
    amountExceedsRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing[2],
      justifyContent: "center",
      marginTop: spacing[3],
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[2],
      borderRadius: radius.lg,
      backgroundColor: colors.status.warning.main + "14",
    },
    amountExceedsText: {
      flexShrink: 1,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      fontSize: typography.fontSize.sm,
      color: colors.status.warning.main,
    },

    // ── Category grid — tinted-fill selection instead of thick borders ──
    categorySection: {
      marginBottom: spacing[6],
    },
    categoryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing[3],
    },
    viewAll: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.primary.main,
    },
    categoryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing[2.5],
    },
    categoryItem: {
      width: "31%",
      borderRadius: radius.lg,
      paddingVertical: spacing[3],
      paddingHorizontal: spacing[2],
      alignItems: "center",
      borderWidth: 1.5,
      position: "relative",
    },
    categoryIconWrap: {
      width: 44,
      height: 44,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing[2],
    },
    categoryLabel: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      textAlign: "center",
    },
    categoryCheck: {
      position: "absolute",
      top: 6,
      right: 6,
      width: 16,
      height: 16,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },

    // ── Ledger-style field rows (date/notes), matching Add Income ───
    field: {
      marginBottom: 0,
    },
    divider: {
      borderBottomWidth: 1.5,
      borderStyle: "dashed",
      borderBottomColor: colors.border.default,
      marginVertical: spacing[5],
    },
    rowLabel: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[2],
      marginBottom: spacing[2.5],
    },
    rowIconBadge: {
      width: 22,
      height: 22,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary.main + "14",
    },
    fieldLabel: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.text.primary,
    },
    notesInput: {
      minHeight: 100,
      padding: spacing[3.5],
      borderRadius: radius.md,
      borderWidth: 1,
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Medium,
      textAlignVertical: "top",
      backgroundColor: colors.background.surface,
      borderColor: colors.border.default,
      color: colors.text.primary,
    },
    notesFieldContainer: {
      backgroundColor: colors.background.surface,
      borderColor: colors.border.default,
      minHeight: 96,
      alignItems: "flex-start",
      paddingVertical: spacing[3],
      borderRadius: radius.lg,
    },
    notesFieldText: {
      color: colors.text.primary,
      minHeight: 72,
      textAlignVertical: "top",
    },

    // ── Footer — spending summary + Save ────────────────────────────
    footer: {
      paddingHorizontal: spacing[6],
      paddingTop: spacing[4],
      paddingBottom: spacing[6],
      backgroundColor: colors.background.screen,
      borderTopWidth: 1,
      borderTopColor: colors.border.default,
    },
    summaryStrip: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing[2.5],
      marginBottom: spacing[4],
      paddingLeft: spacing[3],
      borderLeftWidth: 2,
      borderLeftColor: colors.status.error.main,
    },
    summaryTextCol: {
      flex: 1,
    },
    summaryMeta: {
      fontSize: 10,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      letterSpacing: 0.5,
      marginBottom: 2,
      color: colors.text.secondary,
    },
    summaryLine: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Medium,
      color: colors.text.primary,
    },
    saveBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing[2],
      backgroundColor: colors.primary.main,
      borderRadius: radius.full,
      paddingVertical: spacing[3.5],
      paddingHorizontal: spacing[4],
    },
    saveBtnText: {
      color: colors.primary.contrastText,
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
    },

    // ── Existing keys used by sub-components — unchanged ──────────
    modalBackground: {
      borderTopLeftRadius: radius.xl,
      borderTopRightRadius: radius.xl,
      backgroundColor: colors.background.surface,
    },
    modalTitle: {
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Bold,
      textAlign: "center",
      paddingVertical: spacing[4],
      paddingHorizontal: spacing[6],
      color: colors.text.primary,
    },
    modalListContent: {
      paddingHorizontal: spacing[6],
      paddingBottom: spacing[8.5],
    },
    categoryOptionRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: spacing[3.5],
      borderBottomWidth: 1,
      borderBottomColor: colors.border.default,
    },
    categoryOptionIconWrap: {
      width: 44,
      height: 44,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginRight: spacing[3.5],
    },
    categoryOptionLabel: {
      flex: 1,
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.text.primary,
    },
    emptyWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: spacing[8],
      paddingVertical: spacing[10],
    },
    emptyIconBadge: {
      width: 56,
      height: 56,
      borderRadius: radius.full,
      backgroundColor: colors.background.surfaceAlt,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing[4],
    },
    emptyTitle: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
      marginBottom: spacing[1.5],
      textAlign: "center",
    },
    emptyMessage: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.Medium,
      color: colors.text.secondary,
      textAlign: "center",
      lineHeight: 20,
    },
    incomeModalTitle: {
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Bold,
      textAlign: "center",
      paddingVertical: spacing[4],
      paddingHorizontal: spacing[6],
      color: colors.text.primary,
    },
    incomeModalScrollContent: {
      paddingHorizontal: spacing[6],
      paddingBottom: spacing[8.5],
    },
    incomeSourceCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: spacing[3.5],
      borderRadius: radius.lg,
      borderWidth: 2,
      marginBottom: spacing[3],
      backgroundColor: colors.background.surface,
      borderColor: colors.border.default,
    },
    incomeSourceIconWrap: {
      width: 48,
      height: 48,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginRight: spacing[3.5],
    },
    incomeSourceBody: {
      flex: 1,
      minWidth: 0,
    },
    incomeSourceLabel: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
    },
    incomeSourceRemaining: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      marginTop: spacing[0.5],
      color: colors.text.secondary,
    },
    incomeSourceTotal: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.Medium,
      marginTop: spacing[0.5],
      color: colors.text.muted,
    },
    incomeSourceBarWrap: {
      height: 6,
      borderRadius: radius.sm,
      overflow: "hidden",
      marginTop: spacing[2],
      backgroundColor: colors.background.surfaceAlt,
    },
    incomeSourceBarFill: {
      height: "100%",
      borderRadius: radius.sm,
    },
    incomeSourceRight: {
      alignItems: "flex-end",
      marginLeft: spacing[3],
    },
    incomeSourcePct: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.Medium,
      marginBottom: spacing[1.5],
      color: colors.text.secondary,
    },
    incomeSourceRadio: {
      width: 22,
      height: 22,
      borderRadius: radius.full,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      borderColor: colors.border.default,
    },
    incomeSourceRadioInner: {
      width: 12,
      height: 12,
      borderRadius: radius.full,
      backgroundColor: colors.primary.main,
    },
    incomeSourceConfirmBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing[2],
      paddingVertical: spacing[3.5],
      borderRadius: radius.lg,
      marginTop: spacing[2],
      backgroundColor: colors.primary.main,
    },
    incomeSourceConfirmBtnText: {
      color: colors.primary.contrastText,
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
    },
    incomeSourceConfirmBtnWrap: {
      justifyContent: "space-between",
      marginTop: spacing[4],
      padding: spacing[6],
    },
  }),
);
