import { makeStyles } from "@/theme";

export const useTransactionDetailsStyles = makeStyles(
  ({ colors, spacing, radius, typography }) => ({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background.surface,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[3],
      minHeight: 48,
    },
    headerBtn: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
    },
    scroll: { flex: 1 },
    scrollContent: {
      paddingHorizontal: spacing[5],
      paddingBottom: spacing[8],
    },
    hero: {
      alignItems: "center",
      paddingTop: spacing[2],
      paddingBottom: spacing[4],
    },
    heroIconOuter: {
      width: 72,
      height: 72,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing[3],
    },
    heroIconInner: {
      width: 56,
      height: 56,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
    },
    amount: {
      fontSize: typography.fontSize["7xl"],
      fontFamily: typography.fontFamily.Manrope.Bold,
      marginBottom: spacing[1],
    },
    categoryTitle: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.text.primary,
    },
    metaLine: {
      marginTop: spacing[2],
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Inter.Medium,
      color: colors.text.secondary,
    },
    card: {
      borderRadius: radius.lg,
      backgroundColor: colors.background.surfaceAlt,
      padding: spacing[4],
      marginBottom: spacing[3],
    },
    cardRowHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing[4],
    },
    cardLabelCaps: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Inter.SemiBold,
      letterSpacing: 0.6,
      color: colors.text.secondary,
    },
    sourceAccent: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.primary.main,
    },
    flowRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "space-between",
    },
    flowCol: {
      flex: 1,
    },
    flowColRight: {
      alignItems: "flex-end",
    },
    flowMicro: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Inter.Medium,
      color: colors.text.secondary,
      marginBottom: spacing[1],
    },
    flowValue: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Inter.SemiBold,
      color: colors.text.primary,
    },
    flowValueAfter: {
      color: colors.primary.main,
    },
    flowArrow: {
      paddingHorizontal: spacing[2],
      paddingBottom: spacing[1],
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: spacing[2],
      borderBottomWidth: 1,
      borderBottomColor: `${colors.border.default}55`,
    },
    infoRowFirst: {
      paddingTop: 0,
      borderTopWidth: 0,
    },
    infoRowLast: {
      borderBottomWidth: 0,
    },
    infoLabel: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Inter.Medium,
      color: colors.text.secondary,
    },
    infoValue: {
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Inter.Medium,
      color: colors.text.primary,
      flex: 1,
      textAlign: "right",
      marginLeft: spacing[3],
    },
    notesHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: spacing[2],
    },
    tagPill: {
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[1],
      borderRadius: radius.full,
      backgroundColor: `${colors.primary.main}28`,
    },
    tagPillText: {
      fontSize: typography.fontSize.xs,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.primary.main,
    },
    notesBody: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Inter.Medium,
      color: colors.text.primary,
      lineHeight: 22,
    },
    receipt: {
      marginTop: spacing[4],
      width: "100%",
      height: 160,
      borderRadius: radius.lg,
      backgroundColor: colors.background.surfaceAlt,
    },
    footer: {
      paddingHorizontal: spacing[5],
      paddingTop: spacing[2],
      paddingBottom: spacing[6],
    },
    editBtnOuter: {
      borderRadius: radius.lg,
      overflow: "hidden",
    },
    editBtn: {
      paddingVertical: spacing[4],
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary.main,
    },
    editBtnText: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.primary.contrastText,
    },
    deleteText: {
      marginTop: spacing[4],
      textAlign: "center",
      fontSize: typography.fontSize.sm,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.status.error.main,
    },
    centerBlock: {
      flex: 1,
      padding: spacing[6],
      alignItems: "center",
      justifyContent: "center",
    },
    deleteOverlay: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(0,0,0,0.5)",
      padding: spacing[4],
    },
    deleteBackdrop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    deleteSheet: {
      backgroundColor: colors.background.surface,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: `${colors.border.default}66`,
    },
    deleteHandle: {
      width: 56,
      height: 4,
      borderRadius: radius.full,
      backgroundColor: `${colors.text.secondary}55`,
      marginBottom: spacing[4],
    },
    deleteIconWrap: {
      width: 52,
      height: 52,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background.surfaceAlt,
      marginBottom: spacing[4],
    },
    deleteTitle: {
      fontSize: typography.fontSize["3xl"],
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.text.primary,
      marginBottom: spacing[2],
      textAlign: "center",
    },
    deleteMessage: {
      fontSize: typography.fontSize.lg,
      fontFamily: typography.fontFamily.Inter.Medium,
      color: colors.text.secondary,
      textAlign: "center",
      lineHeight: 24,
      marginBottom: spacing[5],
    },
    deletePrimaryBtn: {
      width: "100%",
      height: 52,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.status.error.main,
      marginBottom: spacing[3],
    },
    deletePrimaryBtnText: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.Bold,
      color: colors.primary.contrastText,
    },
    deleteCancelBtn: {
      width: "100%",
      height: 52,
      borderRadius: radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background.surfaceAlt,
    },
    deleteCancelBtnText: {
      fontSize: typography.fontSize.md,
      fontFamily: typography.fontFamily.Manrope.SemiBold,
      color: colors.text.primary,
    },
  }),
);
